### ISSUE TITLE
显示不全

### ISSUE THREAD

**Issue by Lacetiya** [ChiNoel-osu/FolderThumbnailExplorer#16]
![1](https://user-images.githubusercontent.com/121850407/210333192-c51045a0-c14c-4a5b-9398-98c0b6da24be.png)
![2](https://user-images.githubusercontent.com/121850407/210333203-9da3594c-8f88-49e8-ab01-80c5214f7bb1.png)
图1为全部 到了图2上就少了很多

**Comment by ChiNoel-osu** [comment]
右上角的刷新按钮是黑的 说明还在加载中
说实话我也不知道啥情况 是卡在哪个文件夹了么

**Comment by Lacetiya** [comment]
> 右上角的刷新按钮是黑的 说明还在加载中 说实话我也不知道啥情况 是卡在哪个文件夹了么

我一直开了好久 其他文件夹里面的东西都能加载出来 就放这个文件夹里的加载不全

**Comment by Lacetiya** [comment]
> 右上角的刷新按钮是黑的 说明还在加载中 说实话我也不知道啥情况 是卡在哪个文件夹了么

![3](https://user-images.githubusercontent.com/121850407/210462571-e97cd394-36d2-462e-8b75-02a58c870805.png)
![4](https://user-images.githubusercontent.com/121850407/210462582-793be34f-f649-4944-a7bf-ff115af59f77.png)
第二张里面是第二个文件夹 第二个文件夹里的就全部显示了 第一张到い之后就不显示了

**Comment by ChiNoel-osu** [comment]
可能是卡在哪个文件夹了 可以试着把一直没加载出来的那一个文件夹移动到其他地方看看行不行

**Comment by Lacetiya** [comment]
> 可能是卡在哪个文件夹了 可以试着把一直没加载出来的那一个文件夹移动到其他地方看看行不行

我从后往前试了一下 い之后还可以正常显示 但是一旦把い的放到新文件夹里面之后 就只显示い开头的了

**Comment by Lacetiya** [comment]
> 可能是卡在哪个文件夹了 可以试着把一直没加载出来的那一个文件夹移动到其他地方看看行不行

![5](https://user-images.githubusercontent.com/121850407/210522659-c4176134-6732-4c21-b0ef-fc827d4c4025.png)
![6](https://user-images.githubusercontent.com/121850407/210522672-5661232d-ae06-45aa-a556-2cf1e02ba1d1.png)
图5为移入い的结果 图6为移出い的结果

**Comment by ChiNoel-osu** [comment]
非常抱歉给您带来不便
我感觉是某个文件夹里面的图片有点问题加载不了 您方便的话 可以找出是卡在哪个文件夹了嘛
软件的显示顺序是和资源管理器中按名称升序排序的顺序是一样的 所以被卡住的文件夹应该就是图5最后一个文件夹的下一个文件夹 将其移出到其他地方再试试 也可以单独试着加载被卡住的文件夹

**Comment by Lacetiya** [comment]
> 非常抱歉给您带来不便 我感觉是某个文件夹里面的图片有点问题加载不了 您方便的话 可以找出是卡在哪个文件夹了嘛 软件的显示顺序是和资源管理器中按名称升序排序的顺序是一样的 所以被卡住的文件夹应该就是图5最后一个文件夹的下一个文件夹 将其移出到其他地方再试试 也可以单独试着加载被卡住的文件夹

找到了 那么这几个被卡主的文件夹要怎么办呢 我试着放到了e盘 发现其他文件夹也带着不显示了

**Comment by Lacetiya** [comment]
> 非常抱歉给您带来不便 我感觉是某个文件夹里面的图片有点问题加载不了 您方便的话 可以找出是卡在哪个文件夹了嘛 软件的显示顺序是和资源管理器中按名称升序排序的顺序是一样的 所以被卡住的文件夹应该就是图5最后一个文件夹的下一个文件夹 将其移出到其他地方再试试 也可以单独试着加载被卡住的文件夹

是因为文件损坏吗

**Comment by ChiNoel-osu** [comment]
> 找到了 那么这几个被卡主的文件夹要怎么办呢

看看是否有隐藏的坏图片(后缀是图片但又不是图片)或者其它可疑的东西. 如果方便的话, 最好是把那几个文件夹打包发我一下, 更好Debug, 谢谢!
> 我试着放到了e盘 发现其他文件夹也带着不显示了

因为它排前面, 卡在那里之后软件死磕, 就不会往下了.(看来还是我设计有问题)
> 是因为文件损坏吗

额这个可能吧, 因为加载不出来. 没有原文件夹的话我也不好说.

**Comment by Lacetiya** [comment]
直接在这里发吗？

**Comment by ChiNoel-osu** [comment]
这里发不了文件吧 可以上传到网盘分享给我

**Comment by Lacetiya** [comment]
> 这里发不了文件吧 可以上传到网盘分享给我

https://mega.nz/file/x9NhkaoR#yAXDpyjYns7kHXewdk6UmErdlWDCOYJAuo0KWgeMMZs

**Comment by ChiNoel-osu** [comment]
非常感谢 干完饭就研究一下

**Comment by ChiNoel-osu** [comment]
![Screenshot 2023-01-04 203418](https://user-images.githubusercontent.com/39649720/210559454-f54b4a31-3a94-4428-be9c-ec522d03487e.png)
怎么说嘞 也算是半个文件损坏吧 我的猜想是因为前两张图片用的是比较奇怪的编码格式
已经[修](https://github.com/ChiNoel-osu/FolderThumbnailExplorer/commit/aaad6451b6a84cf71c15de6cfbdef3be0aa411c8)了 可以下载v1.2.4试一试 更新时记得备份Favorites.txt 非常感谢帮忙捉虫

**Comment by Lacetiya** [comment]
> ![Screenshot 2023-01-04 203418](https://user-images.githubusercontent.com/39649720/210559454-f54b4a31-3a94-4428-be9c-ec522d03487e.png) 怎么说嘞 也算是半个文件损坏吧 我的猜想是因为前两张图片用的是比较奇怪的编码格式 已经[修](https://github.com/ChiNoel-osu/FolderThumbnailExplorer/commit/aaad6451b6a84cf71c15de6cfbdef3be0aa411c8)了 可以下载v1.2.4试一试 更新时记得备份Favorites.txt 非常感谢帮忙捉虫

好的 谢谢大佬
