### ISSUE TITLE
排序错误

### ISSUE THREAD

**Issue by Lacetiya** [ChiNoel-osu/FolderThumbnailExplorer#32]
![1](https://github.com/ChiNoel-osu/FolderThumbnailExplorer/assets/121850407/fbf6da45-9d6c-4434-9ab3-3fa7c827af87)
![2](https://github.com/ChiNoel-osu/FolderThumbnailExplorer/assets/121850407/a1691c81-dfd6-483e-8e07-9c9b105ecee0)
![3](https://github.com/ChiNoel-osu/FolderThumbnailExplorer/assets/121850407/83396fa1-d822-4dcd-83cb-87fd433518f7)

**Comment by ChiNoel-osu** [comment]
@Lacetiya 文件夹是不额外进行排序的（即按名称非自然排序）。在Windows资源管理器中，会对文件夹按名称进行自然排序再显示。所以两边顺序可能不同。
代码中已经加入排序方式（按时间、顺序倒序等）但最近没啥时间出新版本。文件夹排序我有时间的话也试着加进去。

**Comment by Lacetiya** [comment]
好的 用了一段时间感觉挺好用的（）坐等新版本

**Comment by ChiNoel-osu** [comment]
问题还在别关issue呀_(:з)∠)_

**Comment by Lacetiya** [comment]
顺带提一嘴 略缩图预览有时候也会错 本的封面点开之后是另一个本的封面

**Comment by ChiNoel-osu** [comment]
> 顺带提一嘴 略缩图预览有时候也会错 本的封面点开之后是另一个本的封面

这个应该已经在 https://github.com/ChiNoel-osu/FolderThumbnailExplorer/commit/0161a3b26c0ac7b0999819c085ed714befe5caf4 修了。当时是如果两个本的文件夹名称的ASCII字符相同，会出现缓存重复的问题。

哎 最近都没啥心思管这软件了 有了工作之后都没啥时间...( ＿ ＿)ノ｜

**Comment by ChiNoel-osu** [comment]
Resolved with the release of 1.4.0.
