### ISSUE TITLE
排序错误

### ISSUE THREAD

**Issue by Lacetiya** [ChiNoel-osu/FolderThumbnailExplorer#34]
前面以前就有的本子是正常排序 后面新加的本子好像默认时间排序

**Comment by Lacetiya** [comment]
![Uploading }O~EVU(SS46_VT5PIQ})`L6.png…]()

**Comment by ChiNoel-osu** [comment]
不太明白...手动改下排序方式有用么
图片好像没有传上来喔

**Comment by Lacetiya** [comment]
![}O~EVU(SS46_VT5PIQ})`L6](https://github.com/user-attachments/assets/88af947f-5026-4012-929f-a798590d13a3)

**Comment by Lacetiya** [comment]
![1}6_4%D1B}GNRUDBI8ENC](https://github.com/user-attachments/assets/0da4db1b-30de-4cba-96d6-201c6013f012)

**Comment by Lacetiya** [comment]
![%W8Q``W`9_)_V$8DP%_MFLJ](https://github.com/user-attachments/assets/ce499284-d0c1-46a6-8c57-c2e9b7463e20)

**Comment by Lacetiya** [comment]
![image](https://github.com/user-attachments/assets/5f3c1171-4b26-40d6-b1f1-9fa740e88e93)
这是windows上按顺序排的 上面的是按修改时间

**Comment by Lacetiya** [comment]
手动无作用 也删了缓存重新加载

**Comment by ChiNoel-osu** [comment]
不清楚什么问题

如果可以的话请帮忙试一下这个版本：[ListDirLog.zip](https://github.com/user-attachments/files/18268614/ListDirLog.zip)
加了一些Log（在Logs文件夹里），可以看到程序拿到的未排序列表是怎样的。

**Comment by Lacetiya** [comment]
[2024-12-29.txt](https://github.com/user-attachments/files/18269044/2024-12-29.tx

**Comment by ChiNoel-osu** [comment]
> [2024-12-29.txt](https://github.com/user-attachments/files/18269044/2024-12-29.tx

这个Log好像没发上来😐

**Comment by Lacetiya** [comment]
[2024-12-29.txt](https://github.com/user-attachments/files/18279020/2024-12-29.txt)

**Comment by ChiNoel-osu** [comment]
从Log来看，`Directory.GetDirectories()`得到的文件夹列表是有问题的，而代码中如果排序方式是默认或名称排序的话，其实并不会对结果进行排序。
把排序加上的话应该就可以。

**Comment by ChiNoel-osu** [comment]
试一下这个吧 [v1.4.1_Beta.zip](https://github.com/user-attachments/files/18279535/v1.4.1_Beta.zip)
这个版本里自然排序为默认，但你可以选择“名称, 顺序"这个排序方式看看还会不会乱。

**Comment by Lacetiya** [comment]
可以了 谢谢佬

**Comment by ChiNoel-osu** [comment]
Closed as fixed
Will be part of v1.4.1 or later
